sonar.projectKey=paudang_mono-repo
sonar.organization=paudang
sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8

# Modules
sonar.modules=backend,frontend

# Backend
backend.sonar.projectName=Backend
backend.sonar.sources=src
backend.sonar.tests=src
backend.sonar.test.inclusions=**/*.test.ts,**/*.spec.ts
backend.sonar.javascript.lcov.reportPaths=coverage/lcov.info
backend.sonar.typescript.lcov.reportPaths=coverage/lcov.info

# Frontend
frontend.sonar.projectName=Frontend
frontend.sonar.sources=src
frontend.sonar.tests=src
frontend.sonar.test.inclusions=**/*.test.tsx,**/*.spec.tsx
frontend.sonar.javascript.lcov.reportPaths=coverage/lcov.info
frontend.sonar.typescript.lcov.reportPaths=coverage/lcov.info
frontend.sonar.exclusions=**/*.css,**/*.svg
